apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: employee-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: nginx:1.31.3
        ports:
        - containerPort: 80

        volumeMounts:
         - name: frontend-assets #vl name
           mountPath: /usr/share/nginx/html/index.html
           subPath: index.html

         - name: frontend-assets #vl name
           mountPath: /usr/share/nginx/html/app.js
           subPath: app.js

         - name: frontend-assets #vl name
           mountPath: /usr/share/nginx/html/style.css
           subPath: style.css

      volumes:
      - name: frontend-assets # volume name
        configMap:
          name: frontend-assets # cm name
