apiVersion: v1
data:
  app.js: "async function loadHealth() {\n\n    try {\n\n        const response =
    await fetch(\"/api/health\");\n\n        const data = await response.json();\n\n
    \       document.getElementById(\"backend-status\").innerHTML =\n            `Backend
    : <span class=\"running\">\U0001F7E2 ${data.status}</span>`;\n\n    } catch {\n\n
    \       document.getElementById(\"backend-status\").innerHTML =\n            `Backend
    : <span class=\"down\">\U0001F534 DOWN</span>`;\n    }\n\n}\n\nasync function
    loadEmployees() {\n\n    try {\n\n        const response = await fetch(\"/api/employees\");\n\n
    \       const employees = await response.json();\n\n        const table = document.getElementById(\"employee-table\");\n\n
    \       table.innerHTML = \"\";\n\n        employees.forEach(emp => {\n\n            table.innerHTML
    += `\n                <tr>\n                    <td>${emp.id}</td>\n                    <td>${emp.name}</td>\n
    \                   <td>${emp.department}</td>\n                </tr>\n            `;\n\n
    \       });\n\n    } catch {\n\n        console.log(\"Unable to load employees\");\n\n
    \   }\n\n}\n\nloadHealth();\n\nloadEmployees();\n"
  index.html: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n
    \   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n
    \   <title>EMS Pro</title>\n\n    <link rel=\"stylesheet\" href=\"style.css\">\n</head>\n\n<body>\n\n<header>\n
    \   <h1>Employee Management System</h1>\n    <p>Kubernetes Mini Project</p>\n</header>\n\n<div
    class=\"status\">\n\n    <div id=\"frontend-status\">\n        Frontend :\n        <span
    class=\"running\">\U0001F7E2 Running</span>\n    </div>\n\n    <div id=\"backend-status\">\n
    \       Backend :\n        <span class=\"loading\">\U0001F7E1 Checking...</span>\n
    \   </div>\n\n    <div id=\"database-status\">\n        Database :\n        <span
    class=\"loading\">\U0001F7E1 Coming Soon</span>\n    </div>\n\n</div>\n\n<h2>Employees</h2>\n\n<table>\n\n<thead>\n<tr>\n<th>ID</th>\n<th>Name</th>\n<th>Department</th>\n</tr>\n</thead>\n\n<tbody
    id=\"employee-table\">\n\n</tbody>\n\n</table>\n\n<script src=\"app.js\"></script>\n\n</body>\n</html>\n"
  style.css: |
    body{
        font-family:Arial,Helvetica,sans-serif;
        margin:40px;
        background:#f4f6f9;
    }

    header{
        text-align:center;
        background:#1565c0;
        color:white;
        padding:20px;
    }

    .status{
        margin:25px 0;
        padding:15px;
        background:white;
        border-radius:8px;
    }

    table{
        width:100%;
        border-collapse:collapse;
        background:white;
    }

    th,td{
        border:1px solid #ddd;
        padding:12px;
    }

    th{
        background:#1565c0;
        color:white;
    }

    .running{
        color:green;
        font-weight:bold;
    }

    .loading{
        color:orange;
        font-weight:bold;
    }

    .down{
        color:red;
        font-weight:bold;
    }
kind: ConfigMap
metadata:
  name: frontend-assets
  namespace: employee-app
